import type {
  BrandProfile,
  UserProfile,
  Campaign,
  Application,
  ChallengeSubmission,
  BrandPoints,
  Reward,
  Notification,
} from './types'

// ── Brand Profiles ──────────────────────────────────────────────────────────
export const mockBrands: BrandProfile[] = [
  {
    id: 'brand-1',
    userId: 'user-brand-1',
    name: 'Nike',
    description: 'Just Do It. Líder mundial en ropa deportiva y calzado.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg',
    industry: 'Deportes & Moda',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'brand-2',
    userId: 'user-brand-2',
    name: 'Adidas',
    description: 'Impossible is Nothing. Marca global de deporte y lifestyle.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg',
    industry: 'Deportes & Moda',
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'brand-3',
    userId: 'user-brand-3',
    name: 'Spotify',
    description: 'Music for everyone. La plataforma de streaming de audio más grande del mundo.',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Spotify_logo_with_text.svg',
    industry: 'Tecnología & Música',
    createdAt: '2024-02-01T10:00:00Z',
  },
]

// ── User/Creator Profiles ───────────────────────────────────────────────────
export const mockUsers: UserProfile[] = [
  {
    id: 'profile-1',
    userId: 'user-1',
    username: 'sofia_creates',
    bio: 'Creadora de contenido lifestyle & fitness. Apasionada del deporte y la vida saludable. 🏃‍♀️✨',
    profileImage: 'https://i.pravatar.cc/150?img=1',
    instagramUrl: 'https://instagram.com/sofia_creates',
    tiktokUrl: 'https://tiktok.com/@sofia_creates',
    followersInstagram: 245000,
    followersTiktok: 180000,
    followersYoutube: 0,
    totalPoints: 12500,
    level: 'Diamond',
    category: 'Fitness & Lifestyle',
    location: 'Buenos Aires, AR',
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: 'profile-2',
    userId: 'user-2',
    username: 'mateo_tech',
    bio: 'Tech reviewer & gadget lover. Unboxings y reviews honestos cada semana.',
    profileImage: 'https://i.pravatar.cc/150?img=3',
    instagramUrl: 'https://instagram.com/mateo_tech',
    tiktokUrl: 'https://tiktok.com/@mateo_tech',
    followersInstagram: 87000,
    followersTiktok: 124000,
    followersYoutube: 45000,
    totalPoints: 7800,
    level: 'Platinum',
    category: 'Tecnología',
    location: 'Córdoba, AR',
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'profile-3',
    userId: 'user-3',
    username: 'lucia_foodie',
    bio: 'Chef amateur & food photographer. Recetas fáciles y deliciosas para todos. 🍕🍜',
    profileImage: 'https://i.pravatar.cc/150?img=5',
    instagramUrl: 'https://instagram.com/lucia_foodie',
    followersInstagram: 156000,
    followersTiktok: 92000,
    followersYoutube: 28000,
    totalPoints: 9200,
    level: 'Gold',
    category: 'Gastronomía',
    location: 'Mendoza, AR',
    createdAt: '2024-02-01T09:00:00Z',
  },
  {
    id: 'profile-4',
    userId: 'user-4',
    username: 'pedro_travels',
    bio: 'Viajero compulsivo. 50+ países visitados. Tips de viaje y aventuras al natural.',
    profileImage: 'https://i.pravatar.cc/150?img=7',
    instagramUrl: 'https://instagram.com/pedro_travels',
    youtubeUrl: 'https://youtube.com/@pedro_travels',
    followersInstagram: 320000,
    followersTiktok: 0,
    followersYoutube: 89000,
    totalPoints: 15200,
    level: 'Diamond',
    category: 'Viajes',
    location: 'Rosario, AR',
    createdAt: '2023-12-01T09:00:00Z',
  },
  {
    id: 'profile-5',
    userId: 'user-5',
    username: 'ana_beauty',
    bio: 'Beauty & skincare enthusiast. Tutoriales de maquillaje y reseñas de productos.',
    profileImage: 'https://i.pravatar.cc/150?img=9',
    instagramUrl: 'https://instagram.com/ana_beauty',
    tiktokUrl: 'https://tiktok.com/@ana_beauty',
    followersInstagram: 58000,
    followersTiktok: 73000,
    followersYoutube: 0,
    totalPoints: 4200,
    level: 'Silver',
    category: 'Belleza & Moda',
    location: 'Buenos Aires, AR',
    createdAt: '2024-03-01T09:00:00Z',
  },
  {
    id: 'profile-6',
    userId: 'user-6',
    username: 'carlos_music',
    bio: 'Músico independiente & productor. Covers, originals y detrás de escenas del proceso creativo.',
    profileImage: 'https://i.pravatar.cc/150?img=12',
    instagramUrl: 'https://instagram.com/carlos_music',
    youtubeUrl: 'https://youtube.com/@carlos_music',
    followersInstagram: 34000,
    followersTiktok: 28000,
    followersYoutube: 67000,
    totalPoints: 3100,
    level: 'Silver',
    category: 'Música & Entretenimiento',
    location: 'La Plata, AR',
    createdAt: '2024-02-15T09:00:00Z',
  },
  {
    id: 'profile-7',
    userId: 'user-7',
    username: 'valentina_fit',
    bio: 'Personal trainer certificada. Rutinas de entrenamiento, nutrición y motivación diaria.',
    profileImage: 'https://i.pravatar.cc/150?img=16',
    instagramUrl: 'https://instagram.com/valentina_fit',
    tiktokUrl: 'https://tiktok.com/@valentina_fit',
    followersInstagram: 112000,
    followersTiktok: 95000,
    followersYoutube: 0,
    totalPoints: 6800,
    level: 'Gold',
    category: 'Fitness & Salud',
    location: 'Buenos Aires, AR',
    createdAt: '2024-01-25T09:00:00Z',
  },
  {
    id: 'profile-8',
    userId: 'user-8',
    username: 'diego_gamer',
    bio: 'Streamer & gamer pro. Reviews, gameplays y torneos en vivo. GG EZ.',
    profileImage: 'https://i.pravatar.cc/150?img=20',
    tiktokUrl: 'https://tiktok.com/@diego_gamer',
    youtubeUrl: 'https://youtube.com/@diego_gamer',
    followersInstagram: 0,
    followersTiktok: 145000,
    followersYoutube: 112000,
    totalPoints: 1500,
    level: 'Bronze',
    category: 'Gaming',
    location: 'Tucumán, AR',
    createdAt: '2024-04-01T09:00:00Z',
  },
]

// ── Campaigns ───────────────────────────────────────────────────────────────
export const mockCampaigns: Campaign[] = [
  {
    id: 'campaign-1',
    brandId: 'brand-1',
    brandName: 'Nike',
    brandLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg',
    type: 'exchange',
    title: 'Air Max Day 2025 - Embajadores',
    description: 'Buscamos creadores apasionados por el deporte y el streetwear para celebrar el Air Max Day. Comparte tu estilo con las nuevas Air Max 2025.',
    status: 'active',
    createdAt: '2025-03-01T10:00:00Z',
    exchange: {
      id: 'exchange-1',
      campaignId: 'campaign-1',
      requirements: {
        followers: 'Mínimo 10,000 seguidores en Instagram o TikTok',
        content: '2 posts + 3 stories en Instagram o TikTok',
        niche: 'Fitness, deportes o streetwear',
      },
      rewardDescription: 'Par de Nike Air Max 2025 + $15,000 ARS',
      rewardType: 'both',
      moneyAmount: 15000,
      productDescription: 'Par de Nike Air Max 2025 (a elección de talle y color)',
      slots: 10,
      deadline: '2025-04-15T23:59:00Z',
      applicantsCount: 34,
    },
  },
  {
    id: 'campaign-2',
    brandId: 'brand-1',
    brandName: 'Nike',
    brandLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg',
    type: 'challenge',
    title: 'Nike 30-Day Running Challenge',
    description: 'Únete a nuestro reto de 30 días corriendo. Comparte tu progreso diario y motiva a tu comunidad. El mejor creador gana premios increíbles.',
    status: 'active',
    createdAt: '2025-02-15T10:00:00Z',
    challenge: {
      id: 'challenge-1',
      campaignId: 'campaign-2',
      isMultiDay: true,
      totalDays: 7,
      hasLeaderboard: true,
      maxWinners: 3,
      days: [
        {
          id: 'day-1',
          challengeId: 'challenge-1',
          dayNumber: 1,
          title: 'Día 1: Tu punto de partida',
          description: 'Comparte tu primera corrida del reto',
          contentType: 'video',
          instructions: 'Graba un video de al menos 30 segundos corriendo. Muestra tu ruta y tiempo. Usa el hashtag #NikeRunChallenge',
        },
        {
          id: 'day-2',
          challengeId: 'challenge-1',
          dayNumber: 2,
          title: 'Día 2: Tu motivación',
          description: '¿Qué te motiva a correr?',
          contentType: 'image',
          instructions: 'Sube una foto inspiracional con tu equipo Nike. Escribe una caption sobre tu motivación.',
        },
        {
          id: 'day-3',
          challengeId: 'challenge-1',
          dayNumber: 3,
          title: 'Día 3: Nuevo récord',
          description: 'Intenta tu mejor tiempo o distancia',
          contentType: 'video',
          instructions: 'Video mostrando tu récord personal. ¡Celebra el logro con tu comunidad!',
        },
        {
          id: 'day-4',
          challengeId: 'challenge-1',
          dayNumber: 4,
          title: 'Día 4: Recuperación activa',
          description: 'Muestra tu rutina de recuperación',
          contentType: 'video',
          instructions: 'Comparte tu stretching post-run o workout de recuperación.',
        },
        {
          id: 'day-5',
          challengeId: 'challenge-1',
          dayNumber: 5,
          title: 'Día 5: Invita a un amigo',
          description: 'Haz que alguien se una al reto',
          contentType: 'image',
          instructions: 'Foto corriendo con un amigo o etiqueta a alguien para unirse.',
        },
        {
          id: 'day-6',
          challengeId: 'challenge-1',
          dayNumber: 6,
          title: 'Día 6: Ruta favorita',
          description: 'Comparte tu ruta favorita',
          contentType: 'image',
          instructions: 'Foto de tu ruta favorita con descripción de por qué la amás.',
        },
        {
          id: 'day-7',
          challengeId: 'challenge-1',
          dayNumber: 7,
          title: 'Día 7: Balance final',
          description: 'Reflexiona sobre la semana',
          contentType: 'video',
          instructions: 'Video resumen de tu semana. ¿Qué aprendiste? ¿Cómo te sentiste?',
        },
      ],
    },
  },
  {
    id: 'campaign-3',
    brandId: 'brand-2',
    brandName: 'Adidas',
    brandLogo: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg',
    type: 'exchange',
    title: 'Colección Originals Verano 2025',
    description: 'La nueva colección Originals llegó para quedarse. Buscamos creadores urbanos que representen el estilo auténtico de Adidas.',
    status: 'active',
    createdAt: '2025-03-05T10:00:00Z',
    exchange: {
      id: 'exchange-3',
      campaignId: 'campaign-3',
      requirements: {
        followers: 'Mínimo 5,000 seguidores',
        content: '1 reel + 4 stories por semana durante 2 semanas',
        niche: 'Moda, lifestyle, streetwear o deporte',
      },
      rewardDescription: 'Outfit completo Adidas Originals (remera + pantalón + zapatillas)',
      rewardType: 'product',
      productDescription: 'Outfit completo Adidas Originals a elección',
      slots: 15,
      deadline: '2025-05-01T23:59:00Z',
      applicantsCount: 52,
    },
  },
  {
    id: 'campaign-4',
    brandId: 'brand-2',
    brandName: 'Adidas',
    brandLogo: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg',
    type: 'challenge',
    title: 'Adidas Style Challenge',
    description: 'Muestra tu creatividad con Adidas. Crea contenido único que inspire a otros y gana premios exclusivos.',
    status: 'active',
    createdAt: '2025-03-10T10:00:00Z',
    challenge: {
      id: 'challenge-4',
      campaignId: 'campaign-4',
      isMultiDay: false,
      totalDays: 1,
      hasLeaderboard: true,
      maxWinners: 5,
      days: [
        {
          id: 'day-4-1',
          challengeId: 'challenge-4',
          dayNumber: 1,
          title: 'Tu look Adidas',
          description: 'Crea el outfit Adidas más creativo',
          contentType: 'image',
          instructions: 'Sube una foto con tu mejor outfit Adidas. Sé creativo con los ángulos y el styling. Usa #AdidasStyleChallenge',
        },
      ],
    },
  },
  {
    id: 'campaign-5',
    brandId: 'brand-3',
    brandName: 'Spotify',
    brandLogo: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Spotify_logo_with_text.svg',
    type: 'exchange',
    title: 'Spotify Wrapped Early Access - Creadores',
    description: 'Sé parte del lanzamiento de Spotify Wrapped 2025. Comparte tu estadística musical y motiva a tu audiencia a descubrir su lado musical.',
    status: 'active',
    createdAt: '2025-03-12T10:00:00Z',
    exchange: {
      id: 'exchange-5',
      campaignId: 'campaign-5',
      requirements: {
        followers: 'Mínimo 15,000 seguidores en cualquier plataforma',
        content: '1 reel de Wrapped + 2 stories + 1 post',
        niche: 'Música, entretenimiento, lifestyle o cualquier nicho',
      },
      rewardDescription: '$25,000 ARS + Suscripción Spotify Premium por 1 año',
      rewardType: 'both',
      moneyAmount: 25000,
      productDescription: 'Suscripción Spotify Premium por 1 año',
      slots: 8,
      deadline: '2025-04-30T23:59:00Z',
      applicantsCount: 89,
    },
  },
  {
    id: 'campaign-6',
    brandId: 'brand-3',
    brandName: 'Spotify',
    brandLogo: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Spotify_logo_with_text.svg',
    type: 'challenge',
    title: 'Spotify Playlist Challenge',
    description: 'Crea la playlist perfecta para cada momento. Comparte tus playlists temáticas y gana reconocimiento como curador musical oficial.',
    status: 'draft',
    createdAt: '2025-03-20T10:00:00Z',
    challenge: {
      id: 'challenge-6',
      campaignId: 'campaign-6',
      isMultiDay: true,
      totalDays: 3,
      hasLeaderboard: true,
      maxWinners: 3,
      days: [
        {
          id: 'day-6-1',
          challengeId: 'challenge-6',
          dayNumber: 1,
          title: 'Playlist para trabajar',
          description: 'Crea la playlist perfecta para concentrarse',
          contentType: 'link',
          instructions: 'Comparte el link de tu playlist de Spotify para trabajar o estudiar. Explica tu selección.',
        },
        {
          id: 'day-6-2',
          challengeId: 'challenge-6',
          dayNumber: 2,
          title: 'Playlist para entrenar',
          description: 'La música que te da energía',
          contentType: 'video',
          instructions: 'Video corto mostrando tu playlist workout. ¿Qué canciones no pueden faltar?',
        },
        {
          id: 'day-6-3',
          challengeId: 'challenge-6',
          dayNumber: 3,
          title: 'Playlist para relajar',
          description: 'Música para desconectar',
          contentType: 'link',
          instructions: 'Comparte tu playlist chill. Describe el mood que quiere crear.',
        },
      ],
    },
  },
]

// ── Applications ────────────────────────────────────────────────────────────
export const mockApplications: Application[] = [
  {
    id: 'app-1',
    exchangeId: 'exchange-1',
    userId: 'user-1',
    userProfile: mockUsers[0],
    status: 'accepted',
    proposalText: 'Me encanta Nike y el running! Tengo una comunidad muy engaged de fitness lovers. Puedo crear contenido auténtico mostrando las Air Max en mis entrenos.',
    createdAt: '2025-03-05T14:00:00Z',
  },
  {
    id: 'app-2',
    exchangeId: 'exchange-1',
    userId: 'user-6',
    userProfile: mockUsers[6],
    status: 'applied',
    proposalText: 'Soy PT certificada y mis seguidores confían en mis recomendaciones deportivas. Las Air Max serían perfectas para mi contenido de entrenamientos.',
    createdAt: '2025-03-06T10:00:00Z',
  },
  {
    id: 'app-3',
    exchangeId: 'exchange-1',
    userId: 'user-3',
    userProfile: mockUsers[3],
    status: 'applied',
    proposalText: 'Aunque viajo, uso Nike siempre. Podría mostrar las Air Max en distintas ciudades del mundo, lo cual sería un contenido único.',
    createdAt: '2025-03-07T11:00:00Z',
  },
  {
    id: 'app-4',
    exchangeId: 'exchange-5',
    userId: 'user-1',
    userProfile: mockUsers[0],
    status: 'applied',
    proposalText: 'Spotify es parte de mi vida diaria. Mi comunidad es muy musical y estarían súper interesados en ver mi Wrapped.',
    createdAt: '2025-03-15T16:00:00Z',
  },
  {
    id: 'app-5',
    exchangeId: 'exchange-3',
    userId: 'user-4',
    userProfile: mockUsers[4],
    status: 'rejected',
    proposalText: 'Me encanta el estilo de Adidas Originals. Podría combinar el outfit con looks viajeros únicos.',
    createdAt: '2025-03-10T09:00:00Z',
  },
]

// ── Challenge Submissions ───────────────────────────────────────────────────
export const mockSubmissions: ChallengeSubmission[] = [
  {
    id: 'sub-1',
    challengeId: 'challenge-1',
    dayId: 'day-1',
    userId: 'user-1',
    userProfile: mockUsers[0],
    submissionUrl: 'https://www.tiktok.com/@sofia_creates',
    submissionText: '¡Día 1 del reto Nike! Arranqué con 5km en Palermo. ¡Vamos! 🏃‍♀️',
    score: 95,
    createdAt: '2025-03-16T08:30:00Z',
  },
  {
    id: 'sub-2',
    challengeId: 'challenge-1',
    dayId: 'day-1',
    userId: 'user-6',
    userProfile: mockUsers[6],
    submissionUrl: 'https://www.instagram.com/valentina_fit',
    submissionText: 'Empezando fuerte el #NikeRunChallenge. 8km de calentamiento. 💪',
    score: 88,
    createdAt: '2025-03-16T07:15:00Z',
  },
  {
    id: 'sub-3',
    challengeId: 'challenge-1',
    dayId: 'day-1',
    userId: 'user-1',
    userProfile: mockUsers[0],
    submissionUrl: 'https://www.tiktok.com/@sofia_creates',
    submissionText: 'Día 2: Mi motivación es ver hasta dónde puedo llegar. 🌟',
    score: 92,
    createdAt: '2025-03-17T09:00:00Z',
  },
]

// ── Brand Points per User ───────────────────────────────────────────────────
export const mockBrandPoints: BrandPoints[] = [
  {
    brandId: 'brand-1',
    brandName: 'Nike',
    brandLogo: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg',
    points: 4500,
  },
  {
    brandId: 'brand-2',
    brandName: 'Adidas',
    brandLogo: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg',
    points: 3200,
  },
  {
    brandId: 'brand-3',
    brandName: 'Spotify',
    brandLogo: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Spotify_logo_with_text.svg',
    points: 4800,
  },
]

// ── Rewards ──────────────────────────────────────────────────────────────────
export const mockRewards: Reward[] = [
  // Nike rewards
  {
    id: 'reward-1',
    brandId: 'brand-1',
    title: 'Nike Air Max 2025',
    description: 'Un par de las icónicas Air Max a elección de talle y color.',
    pointsCost: 5000,
    rewardType: 'product',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
  },
  {
    id: 'reward-2',
    brandId: 'brand-1',
    title: '30% descuento en Nike.com',
    description: 'Código de descuento del 30% válido por 30 días en cualquier compra.',
    pointsCost: 1500,
    rewardType: 'discount',
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=400',
  },
  {
    id: 'reward-3',
    brandId: 'brand-1',
    title: 'Visita a Campus Nike',
    description: 'Tour exclusivo al campus de Nike con sesión fotográfica y regalo sorpresa.',
    pointsCost: 8000,
    rewardType: 'experience',
    image: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=400',
  },
  // Adidas rewards
  {
    id: 'reward-4',
    brandId: 'brand-2',
    title: 'Outfit Adidas Originals',
    description: 'Set completo: remera, pantalón y zapatillas de la colección Originals.',
    pointsCost: 4500,
    rewardType: 'product',
    image: 'https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?w=400',
  },
  {
    id: 'reward-5',
    brandId: 'brand-2',
    title: '20% descuento Adidas',
    description: 'Cupón de descuento del 20% para usar en tienda online.',
    pointsCost: 1000,
    rewardType: 'discount',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=400',
  },
  {
    id: 'reward-6',
    brandId: 'brand-2',
    title: 'Acceso a evento Adidas',
    description: 'Invitación VIP al próximo evento de lanzamiento de Adidas en Argentina.',
    pointsCost: 6000,
    rewardType: 'experience',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
  },
  // Spotify rewards
  {
    id: 'reward-7',
    brandId: 'brand-3',
    title: 'Spotify Premium 1 año',
    description: 'Suscripción Premium de Spotify por 12 meses sin interrupciones.',
    pointsCost: 2000,
    rewardType: 'product',
    image: 'https://images.unsplash.com/photo-1611339555312-e607c8352fd7?w=400',
  },
  {
    id: 'reward-8',
    brandId: 'brand-3',
    title: 'Merchandising Spotify',
    description: 'Pack de merchandising oficial: buzo, taza y stickers.',
    pointsCost: 3000,
    rewardType: 'product',
    image: 'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400',
  },
  {
    id: 'reward-9',
    brandId: 'brand-3',
    title: 'Sesión con artista',
    description: 'Meet & Greet exclusivo con un artista top de Spotify Argentina.',
    pointsCost: 10000,
    rewardType: 'experience',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400',
  },
]

// ── Notifications ────────────────────────────────────────────────────────────
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    title: '¡Felicitaciones! Fuiste aceptada',
    message: 'Nike aceptó tu aplicación para "Air Max Day 2025 - Embajadores". ¡Revisá los detalles y comenzá tu colaboración!',
    read: false,
    createdAt: '2025-03-20T15:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    title: 'Nueva campaña disponible',
    message: 'Spotify lanzó una nueva campaña que podría interesarte: "Spotify Wrapped Early Access". ¡Aplicá antes del 30 de abril!',
    read: false,
    createdAt: '2025-03-19T10:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    title: 'Subiste de nivel',
    message: '¡Ahora sos Diamond! Has alcanzado 12,500 puntos. Accedés a beneficios exclusivos y campañas premium.',
    read: true,
    createdAt: '2025-03-18T09:00:00Z',
  },
  {
    id: 'notif-4',
    userId: 'user-1',
    title: 'Nuevo puntaje en el leaderboard',
    message: 'Tu sumisión del Día 3 del Nike Running Challenge recibió 92 puntos. ¡Estás en el 2do lugar!',
    read: true,
    createdAt: '2025-03-17T20:00:00Z',
  },
  {
    id: 'notif-5',
    userId: 'user-1',
    title: 'Recordatorio de deadline',
    message: 'El reto "Nike 30-Day Running Challenge" cierra en 5 días. ¡No olvides entregar tu sumisión del Día 7!',
    read: true,
    createdAt: '2025-03-16T08:00:00Z',
  },
]

// ── Leaderboard (for challenges) ────────────────────────────────────────────
export const mockLeaderboard = [
  { userId: 'user-1', userProfile: mockUsers[0], totalScore: 187, rank: 1 },
  { userId: 'user-6', userProfile: mockUsers[6], totalScore: 172, rank: 2 },
  { userId: 'user-1', userProfile: mockUsers[1], totalScore: 145, rank: 3 },
  { userId: 'user-4', userProfile: mockUsers[3], totalScore: 132, rank: 4 },
  { userId: 'user-2', userProfile: mockUsers[2], totalScore: 98, rank: 5 },
]

// ── Mock accounts for demo ──────────────────────────────────────────────────
export const MOCK_ACCOUNTS = {
  brands: [
    { email: 'nike@brand.com', brandId: 'brand-1' },
    { email: 'adidas@brand.com', brandId: 'brand-2' },
    { email: 'spotify@brand.com', brandId: 'brand-3' },
  ],
  users: [
    { email: 'sofia@user.com', userId: 'user-1' },
    { email: 'mateo@user.com', userId: 'user-2' },
    { email: 'lucia@user.com', userId: 'user-3' },
  ],
}
